---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation stack for CodePipeline resources.
Parameters:
  GitHubOwner:
    Type: String
    Default: jpb80
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: cicd-fargate
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !ImportValue storage-ArtifactsBucketName
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: SourceCode
          Configuration:
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo
            Branch: !Ref GitHubBranch
            PollForSourceChanges: true
            OAuthToken: !Join
              - ''
              - - '{{resolve:secretsmanager:'
                - 'github_auth'
                - ':SecretString:key}}'
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: CodeBuild
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          InputArtifacts:
            - Name: SourceCode
          Configuration:
            ProjectName: codebuild
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: ECS
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: ECS
            Version: '1'
          InputArtifacts:
            - Name: SourceCode
          Configuration:
            ClusterName: !Join
              - ''
              - - '{{resolve:ssm:'
                - 'fargate-EcsClusterName:'
                - '1}}'
            ServiceName: !Join
              - ''
              - - '{{resolve:ssm:'
                - 'fargate-EcsServiceName:'
                - '1}}'
            FileName: imagedefinitions.json
          RunOrder: 1

  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Join
          - ''
          - - '{{resolve:secretsmanager:'
            - 'github_auth'
            - ':SecretString:key}}'
      RegisterWithThirdParty: true
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions
